dist: xenial

language: python

python:
  - "3.7"

install:
  - sudo apt-get install -y python3-pip

script:
  - echo "Hello"

before_deploy:
  - pip3 install awscli --upgrade
  - export PATH=$PATH:$HOME/.local/bin

deploy:
  provider: script
  script: bash ./scripts/upload.sh
  skip_cleanup: true
